// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/admission_decision_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

///  AdmissionDecision is server -> client signaling that conveys the outcome of
///  a room join request. Sent in the `data` field of a PacketWrapper whose
///  `packet_type == ADMISSION_DECISION`.
///
///  Wave 1 (p3-13): emitted only when the soft cap is reached. Admitted joins
///  below the soft cap do NOT receive this packet (no behavioural change for
///  the common path). The "queued" status today is purely informational — the
///  joiner is still fully admitted to the room. Wave 3 will introduce the
///  actual queue/holding-room semantics.
// @@protoc_insertion_point(message:videocall.AdmissionDecision)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AdmissionDecision {
    // message fields
    // @@protoc_insertion_point(field:videocall.AdmissionDecision.status)
    pub status: ::protobuf::EnumOrUnknown<admission_decision::Status>,
    ///  1-based position within the soft-cap overflow zone. Only set for the
    ///  QUEUED and REJECTED statuses. position = current_count - SOFT_CAP + 1,
    ///  so a joiner attempting to enter a 195-member room gets position=1.
    // @@protoc_insertion_point(field:videocall.AdmissionDecision.position)
    pub position: u32,
    ///  Machine-readable reason code. Examples: "room_full" for REJECTED,
    ///  "soft_cap_reached" for QUEUED. Empty for ADMITTED.
    // @@protoc_insertion_point(field:videocall.AdmissionDecision.reason)
    pub reason: ::std::string::String,
    ///  Hint to the client for how long to wait before retrying (seconds).
    ///  Only set for REJECTED. Zero means "no hint".
    // @@protoc_insertion_point(field:videocall.AdmissionDecision.retry_after_secs)
    pub retry_after_secs: u32,
    ///  Target pod headless DNS name. Set only for REDIRECT — format is
    ///  `rustlemania-{transport}-{ordinal}.{transport}-headless.svc.cluster.local`,
    ///  no port (the client reuses its current port). Empty for all other
    ///  statuses.
    // @@protoc_insertion_point(field:videocall.AdmissionDecision.redirect_to)
    pub redirect_to: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:videocall.AdmissionDecision.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AdmissionDecision {
    fn default() -> &'a AdmissionDecision {
        <AdmissionDecision as ::protobuf::Message>::default_instance()
    }
}

impl AdmissionDecision {
    pub fn new() -> AdmissionDecision {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "status",
            |m: &AdmissionDecision| { &m.status },
            |m: &mut AdmissionDecision| { &mut m.status },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "position",
            |m: &AdmissionDecision| { &m.position },
            |m: &mut AdmissionDecision| { &mut m.position },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "reason",
            |m: &AdmissionDecision| { &m.reason },
            |m: &mut AdmissionDecision| { &mut m.reason },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retry_after_secs",
            |m: &AdmissionDecision| { &m.retry_after_secs },
            |m: &mut AdmissionDecision| { &mut m.retry_after_secs },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "redirect_to",
            |m: &AdmissionDecision| { &m.redirect_to },
            |m: &mut AdmissionDecision| { &mut m.redirect_to },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AdmissionDecision>(
            "AdmissionDecision",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AdmissionDecision {
    const NAME: &'static str = "AdmissionDecision";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.status = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.position = is.read_uint32()?;
                },
                26 => {
                    self.reason = is.read_string()?;
                },
                32 => {
                    self.retry_after_secs = is.read_uint32()?;
                },
                42 => {
                    self.redirect_to = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.status != ::protobuf::EnumOrUnknown::new(admission_decision::Status::STATUS_UNKNOWN) {
            my_size += ::protobuf::rt::int32_size(1, self.status.value());
        }
        if self.position != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.position);
        }
        if !self.reason.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.reason);
        }
        if self.retry_after_secs != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.retry_after_secs);
        }
        if !self.redirect_to.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.redirect_to);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.status != ::protobuf::EnumOrUnknown::new(admission_decision::Status::STATUS_UNKNOWN) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.status))?;
        }
        if self.position != 0 {
            os.write_uint32(2, self.position)?;
        }
        if !self.reason.is_empty() {
            os.write_string(3, &self.reason)?;
        }
        if self.retry_after_secs != 0 {
            os.write_uint32(4, self.retry_after_secs)?;
        }
        if !self.redirect_to.is_empty() {
            os.write_string(5, &self.redirect_to)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AdmissionDecision {
        AdmissionDecision::new()
    }

    fn clear(&mut self) {
        self.status = ::protobuf::EnumOrUnknown::new(admission_decision::Status::STATUS_UNKNOWN);
        self.position = 0;
        self.reason.clear();
        self.retry_after_secs = 0;
        self.redirect_to.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AdmissionDecision {
        static instance: AdmissionDecision = AdmissionDecision {
            status: ::protobuf::EnumOrUnknown::from_i32(0),
            position: 0,
            reason: ::std::string::String::new(),
            retry_after_secs: 0,
            redirect_to: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AdmissionDecision {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AdmissionDecision").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AdmissionDecision {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AdmissionDecision {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `AdmissionDecision`
pub mod admission_decision {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:videocall.AdmissionDecision.Status)
    pub enum Status {
        // @@protoc_insertion_point(enum_value:videocall.AdmissionDecision.Status.STATUS_UNKNOWN)
        STATUS_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:videocall.AdmissionDecision.Status.ADMITTED)
        ADMITTED = 1,
        // @@protoc_insertion_point(enum_value:videocall.AdmissionDecision.Status.QUEUED)
        QUEUED = 2,
        // @@protoc_insertion_point(enum_value:videocall.AdmissionDecision.Status.REJECTED)
        REJECTED = 3,
        // @@protoc_insertion_point(enum_value:videocall.AdmissionDecision.Status.REDIRECT)
        REDIRECT = 4,
    }

    impl ::protobuf::Enum for Status {
        const NAME: &'static str = "Status";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Status> {
            match value {
                0 => ::std::option::Option::Some(Status::STATUS_UNKNOWN),
                1 => ::std::option::Option::Some(Status::ADMITTED),
                2 => ::std::option::Option::Some(Status::QUEUED),
                3 => ::std::option::Option::Some(Status::REJECTED),
                4 => ::std::option::Option::Some(Status::REDIRECT),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<Status> {
            match str {
                "STATUS_UNKNOWN" => ::std::option::Option::Some(Status::STATUS_UNKNOWN),
                "ADMITTED" => ::std::option::Option::Some(Status::ADMITTED),
                "QUEUED" => ::std::option::Option::Some(Status::QUEUED),
                "REJECTED" => ::std::option::Option::Some(Status::REJECTED),
                "REDIRECT" => ::std::option::Option::Some(Status::REDIRECT),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Status] = &[
            Status::STATUS_UNKNOWN,
            Status::ADMITTED,
            Status::QUEUED,
            Status::REJECTED,
            Status::REDIRECT,
        ];
    }

    impl ::protobuf::EnumFull for Status {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("AdmissionDecision.Status").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for Status {
        fn default() -> Self {
            Status::STATUS_UNKNOWN
        }
    }

    impl Status {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Status>("AdmissionDecision.Status")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n%types/admission_decision_packet.proto\x12\tvideocall\"\xf4\x01\n\x11A\
    dmissionDecision\x12;\n\x06status\x18\x01\x20\x01(\x0e2#.videocall.Admis\
    sionDecision.StatusR\x06status\x12\x1a\n\x08position\x18\x02\x20\x01(\rR\
    \x08position\x12\x16\n\x06reason\x18\x03\x20\x01(\tR\x06reason\x12(\n\
    \x10retry_after_secs\x18\x04\x20\x01(\rR\x0eretryAfterSecs\"D\n\x06Statu\
    s\x12\x12\n\x0eSTATUS_UNKNOWN\x10\0\x12\x0c\n\x08ADMITTED\x10\x01\x12\n\
    \n\x06QUEUED\x10\x02\x12\x0c\n\x08REJECTED\x10\x03J\xb2\x0f\n\x06\x12\
    \x04\0\0&\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\
    \x01\0\x12\n\x98\x04\n\x02\x04\0\x12\x04\x0c\0&\x01\x1a\x8b\x04\x20Admis\
    sionDecision\x20is\x20server\x20->\x20client\x20signaling\x20that\x20con\
    veys\x20the\x20outcome\x20of\n\x20a\x20room\x20join\x20request.\x20Sent\
    \x20in\x20the\x20`data`\x20field\x20of\x20a\x20PacketWrapper\x20whose\n\
    \x20`packet_type\x20==\x20ADMISSION_DECISION`.\n\n\x20Wave\x201\x20(p3-1\
    3):\x20emitted\x20only\x20when\x20the\x20soft\x20cap\x20is\x20reached.\
    \x20Admitted\x20joins\n\x20below\x20the\x20soft\x20cap\x20do\x20NOT\x20r\
    eceive\x20this\x20packet\x20(no\x20behavioural\x20change\x20for\n\x20the\
    \x20common\x20path).\x20The\x20\"queued\"\x20status\x20today\x20is\x20pu\
    rely\x20informational\x20\xe2\x80\x94\x20the\n\x20joiner\x20is\x20still\
    \x20fully\x20admitted\x20to\x20the\x20room.\x20Wave\x203\x20will\x20intr\
    oduce\x20the\n\x20actual\x20queue/holding-room\x20semantics.\n\n\n\n\x03\
    \x04\0\x01\x12\x03\x0c\x08\x19\n\x0c\n\x04\x04\0\x04\0\x12\x04\r\x02\x19\
    \x03\n\x0c\n\x05\x04\0\x04\0\x01\x12\x03\r\x07\r\n\r\n\x06\x04\0\x04\0\
    \x02\0\x12\x03\x0e\x04\x17\n\x0e\n\x07\x04\0\x04\0\x02\0\x01\x12\x03\x0e\
    \x04\x12\n\x0e\n\x07\x04\0\x04\0\x02\0\x02\x12\x03\x0e\x15\x16\n\xa2\x01\
    \n\x06\x04\0\x04\0\x02\x01\x12\x03\x11\x04\x11\x1a\x92\x01\x20Joiner\x20\
    is\x20admitted\x20to\x20the\x20room.\x20Wave\x201\x20only\x20emits\x20th\
    is\x20status\x20when\x20the\n\x20join\x20occurred\x20above\x20the\x20sof\
    t\x20cap\x20but\x20below\x20the\x20hard\x20cap\x20(informational).\n\n\
    \x0e\n\x07\x04\0\x04\0\x02\x01\x01\x12\x03\x11\x04\x0c\n\x0e\n\x07\x04\0\
    \x04\0\x02\x01\x02\x12\x03\x11\x0f\x10\n\xe5\x01\n\x06\x04\0\x04\0\x02\
    \x02\x12\x03\x15\x04\x0f\x1a\xd5\x01\x20Joiner\x20is\x20admitted\x20but\
    \x20flagged\x20as\x20being\x20in\x20the\x20soft-cap\x20zone.\x20Reserved\
    \n\x20for\x20future\x20wave-3\x20holding-room\x20semantics;\x20in\x20wav\
    e\x201\x20the\x20joiner\x20IS\x20in\n\x20the\x20room\x20and\x20receives\
    \x20media\x20normally\x20\xe2\x80\x94\x20`position`\x20is\x20information\
    al.\n\n\x0e\n\x07\x04\0\x04\0\x02\x02\x01\x12\x03\x15\x04\n\n\x0e\n\x07\
    \x04\0\x04\0\x02\x02\x02\x12\x03\x15\r\x0e\n\x94\x01\n\x06\x04\0\x04\0\
    \x02\x03\x12\x03\x18\x04\x11\x1a\x84\x01\x20Joiner\x20is\x20rejected\x20\
    because\x20the\x20hard\x20cap\x20has\x20been\x20reached.\x20The\x20serve\
    r\n\x20closes\x20the\x20connection\x20immediately\x20after\x20sending\
    \x20this\x20packet.\n\n\x0e\n\x07\x04\0\x04\0\x02\x03\x01\x12\x03\x18\
    \x04\x0c\n\x0e\n\x07\x04\0\x04\0\x02\x03\x02\x12\x03\x18\x0f\x10\n\x0b\n\
    \x04\x04\0\x02\0\x12\x03\x1b\x02\x14\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\
    \x1b\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x1b\t\x0f\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\x1b\x12\x13\n\xe0\x01\n\x04\x04\0\x02\x01\x12\
    \x03\x1f\x02\x16\x1a\xd2\x01\x201-based\x20position\x20within\x20the\x20\
    soft-cap\x20overflow\x20zone.\x20Only\x20set\x20for\x20the\n\x20QUEUED\
    \x20and\x20REJECTED\x20statuses.\x20position\x20=\x20current_count\x20-\
    \x20SOFT_CAP\x20+\x201,\n\x20so\x20a\x20joiner\x20attempting\x20to\x20en\
    ter\x20a\x20195-member\x20room\x20gets\x20position=1.\n\n\x0c\n\x05\x04\
    \0\x02\x01\x05\x12\x03\x1f\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\
    \x1f\t\x11\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x1f\x14\x15\n\x84\x01\n\
    \x04\x04\0\x02\x02\x12\x03\"\x02\x14\x1aw\x20Machine-readable\x20reason\
    \x20code.\x20Examples:\x20\"room_full\"\x20for\x20REJECTED,\n\x20\"soft_\
    cap_reached\"\x20for\x20QUEUED.\x20Empty\x20for\x20ADMITTED.\n\n\x0c\n\
    \x05\x04\0\x02\x02\x05\x12\x03\"\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\
    \x12\x03\"\t\x0f\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\"\x12\x13\n\x7f\n\
    \x04\x04\0\x02\x03\x12\x03%\x02\x1e\x1ar\x20Hint\x20to\x20the\x20client\
    \x20for\x20how\x20long\x20to\x20wait\x20before\x20retrying\x20(seconds).\
    \n\x20Only\x20set\x20for\x20REJECTED.\x20Zero\x20means\x20\"no\x20hint\"\
    .\n\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03%\x02\x08\n\x0c\n\x05\x04\0\x02\
    \x03\x01\x12\x03%\t\x19\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03%\x1c\x1db\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(AdmissionDecision::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(admission_decision::Status::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
