// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/connection_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:ConnectionPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ConnectionPacket {
    // message fields
    // @@protoc_insertion_point(field:ConnectionPacket.meeting_id)
    pub meeting_id: ::std::string::String,
    ///  CAPABILITY BITS:
    ///    SFU_ROUTING_HEADER = 1   // emits MediaPacket.routing_header
    ///    SVC                = 2   // can encode/decode SVC layered bitstreams
    ///    SUBSCRIPTION       = 4   // can emit SubscriptionUpdate
    // @@protoc_insertion_point(field:ConnectionPacket.client_capabilities)
    pub client_capabilities: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:ConnectionPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ConnectionPacket {
    fn default() -> &'a ConnectionPacket {
        <ConnectionPacket as ::protobuf::Message>::default_instance()
    }
}

impl ConnectionPacket {
    pub fn new() -> ConnectionPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "meeting_id",
            |m: &ConnectionPacket| { &m.meeting_id },
            |m: &mut ConnectionPacket| { &mut m.meeting_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "client_capabilities",
            |m: &ConnectionPacket| { &m.client_capabilities },
            |m: &mut ConnectionPacket| { &mut m.client_capabilities },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ConnectionPacket>(
            "ConnectionPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ConnectionPacket {
    const NAME: &'static str = "ConnectionPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.meeting_id = is.read_string()?;
                },
                16 => {
                    self.client_capabilities = ::std::option::Option::Some(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.meeting_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.meeting_id);
        }
        if let Some(v) = self.client_capabilities {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.meeting_id.is_empty() {
            os.write_string(1, &self.meeting_id)?;
        }
        if let Some(v) = self.client_capabilities {
            os.write_uint32(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ConnectionPacket {
        ConnectionPacket::new()
    }

    fn clear(&mut self) {
        self.meeting_id.clear();
        self.client_capabilities = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ConnectionPacket {
        static instance: ConnectionPacket = ConnectionPacket {
            meeting_id: ::std::string::String::new(),
            client_capabilities: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ConnectionPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ConnectionPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ConnectionPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ConnectionPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1dtypes/connection_packet.proto\"\x7f\n\x10ConnectionPacket\x12\x1d\
    \n\nmeeting_id\x18\x01\x20\x01(\tR\tmeetingId\x124\n\x13client_capabilit\
    ies\x18\x02\x20\x01(\rH\0R\x12clientCapabilities\x88\x01\x01B\x16\n\x14_\
    client_capabilitiesJ\xff\x02\n\x06\x12\x04\0\0\n\x01\n\x08\n\x01\x0c\x12\
    \x03\0\0\x12\n\n\n\x02\x04\0\x12\x04\x02\0\n\x01\n\n\n\x03\x04\0\x01\x12\
    \x03\x02\x08\x18\n\x0b\n\x04\x04\0\x02\0\x12\x03\x03\x02\x18\n\x0c\n\x05\
    \x04\0\x02\0\x05\x12\x03\x03\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\
    \x03\t\x13\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x03\x16\x17\n\xe3\x01\n\
    \x04\x04\0\x02\x01\x12\x03\t\x02*\x1a\xd5\x01\x20CAPABILITY\x20BITS:\n\
    \x20\x20\x20SFU_ROUTING_HEADER\x20=\x201\x20\x20\x20//\x20emits\x20Media\
    Packet.routing_header\n\x20\x20\x20SVC\x20\x20\x20\x20\x20\x20\x20\x20\
    \x20\x20\x20\x20\x20\x20\x20\x20=\x202\x20\x20\x20//\x20can\x20encode/de\
    code\x20SVC\x20layered\x20bitstreams\n\x20\x20\x20SUBSCRIPTION\x20\x20\
    \x20\x20\x20\x20\x20=\x204\x20\x20\x20//\x20can\x20emit\x20SubscriptionU\
    pdate\n\n\x0c\n\x05\x04\0\x02\x01\x04\x12\x03\t\x02\n\n\x0c\n\x05\x04\0\
    \x02\x01\x05\x12\x03\t\x0b\x11\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\t\
    \x12%\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\t()b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ConnectionPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
