// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/health_beacon_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

///  HealthBeaconPacket — owner-pod liveness signal for the SFU spillover
///  controller (P6 wave-2 bead vc-kol / p6-7).
///
///  The owner pod for a given room (determined by `affinity::is_owner`)
///  publishes one of these every 5 seconds to `room.{room_id}.system`
///  wrapped in a PacketWrapper with `packet_type = HEALTH_BEACON` and
///  `user_id = SYSTEM_USER_ID`. Spill pods (p6-8) consume the beacon
///  stream to decide whether to accept additional joiners for the room.
///
///  All fields are small primitives — keep the payload tiny so beacons
///  stay cheap at fleet scale (many rooms × 0.2 Hz cadence).
// @@protoc_insertion_point(message:videocall.HealthBeaconPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HealthBeaconPacket {
    // message fields
    ///  Number of members currently tracked in the owner pod's RoomState
    ///  (senders + observers). Drives the participant soft-cap check.
    // @@protoc_insertion_point(field:videocall.HealthBeaconPacket.participant_count)
    pub participant_count: u32,
    ///  Estimated CPU load on the emitting pod, normalised to `[0, 1]`.
    ///  Currently sourced from `/proc/loadavg` 1-min average divided by
    ///  online CPU count on Linux; falls back to 0.0 if the read fails.
    ///  0..1 is the contract the consumer relies on for the soft-cap check.
    // @@protoc_insertion_point(field:videocall.HealthBeaconPacket.cpu_load)
    pub cpu_load: f32,
    ///  Owner pod's wall-clock time at the moment the beacon was assembled,
    ///  expressed as UNIX milliseconds. Lets the consumer estimate the age
    ///  of a beacon against its own clock (and detect stalled emitters).
    // @@protoc_insertion_point(field:videocall.HealthBeaconPacket.reported_at_ms)
    pub reported_at_ms: u64,
    // special fields
    // @@protoc_insertion_point(special_field:videocall.HealthBeaconPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HealthBeaconPacket {
    fn default() -> &'a HealthBeaconPacket {
        <HealthBeaconPacket as ::protobuf::Message>::default_instance()
    }
}

impl HealthBeaconPacket {
    pub fn new() -> HealthBeaconPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "participant_count",
            |m: &HealthBeaconPacket| { &m.participant_count },
            |m: &mut HealthBeaconPacket| { &mut m.participant_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "cpu_load",
            |m: &HealthBeaconPacket| { &m.cpu_load },
            |m: &mut HealthBeaconPacket| { &mut m.cpu_load },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "reported_at_ms",
            |m: &HealthBeaconPacket| { &m.reported_at_ms },
            |m: &mut HealthBeaconPacket| { &mut m.reported_at_ms },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<HealthBeaconPacket>(
            "HealthBeaconPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for HealthBeaconPacket {
    const NAME: &'static str = "HealthBeaconPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                16 => {
                    self.participant_count = is.read_uint32()?;
                },
                29 => {
                    self.cpu_load = is.read_float()?;
                },
                32 => {
                    self.reported_at_ms = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.participant_count != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.participant_count);
        }
        if self.cpu_load != 0. {
            my_size += 1 + 4;
        }
        if self.reported_at_ms != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.reported_at_ms);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.participant_count != 0 {
            os.write_uint32(2, self.participant_count)?;
        }
        if self.cpu_load != 0. {
            os.write_float(3, self.cpu_load)?;
        }
        if self.reported_at_ms != 0 {
            os.write_uint64(4, self.reported_at_ms)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HealthBeaconPacket {
        HealthBeaconPacket::new()
    }

    fn clear(&mut self) {
        self.participant_count = 0;
        self.cpu_load = 0.;
        self.reported_at_ms = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HealthBeaconPacket {
        static instance: HealthBeaconPacket = HealthBeaconPacket {
            participant_count: 0,
            cpu_load: 0.,
            reported_at_ms: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for HealthBeaconPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("HealthBeaconPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for HealthBeaconPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HealthBeaconPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x20types/health_beacon_packet.proto\x12\tvideocall\"\x91\x01\n\x12Hea\
    lthBeaconPacket\x12+\n\x11participant_count\x18\x02\x20\x01(\rR\x10parti\
    cipantCount\x12\x19\n\x08cpu_load\x18\x03\x20\x01(\x02R\x07cpuLoad\x12$\
    \n\x0ereported_at_ms\x18\x04\x20\x01(\x04R\x0creportedAtMsJ\x04\x08\x01\
    \x10\x02R\x07room_idJ\xd7\r\n\x06\x12\x04\0\0%\x01\n\x08\n\x01\x0c\x12\
    \x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x12\n\xd6\x04\n\x02\x04\0\x12\
    \x04\x0f\0%\x01\x1a\xc9\x04\x20HealthBeaconPacket\x20\xe2\x80\x94\x20own\
    er-pod\x20liveness\x20signal\x20for\x20the\x20SFU\x20spillover\n\x20cont\
    roller\x20(P6\x20wave-2\x20bead\x20vc-kol\x20/\x20p6-7).\n\n\x20The\x20o\
    wner\x20pod\x20for\x20a\x20given\x20room\x20(determined\x20by\x20`affini\
    ty::is_owner`)\n\x20publishes\x20one\x20of\x20these\x20every\x205\x20sec\
    onds\x20to\x20`room.{room_id}.system`\n\x20wrapped\x20in\x20a\x20PacketW\
    rapper\x20with\x20`packet_type\x20=\x20HEALTH_BEACON`\x20and\n\x20`user_\
    id\x20=\x20SYSTEM_USER_ID`.\x20Spill\x20pods\x20(p6-8)\x20consume\x20the\
    \x20beacon\n\x20stream\x20to\x20decide\x20whether\x20to\x20accept\x20add\
    itional\x20joiners\x20for\x20the\x20room.\n\n\x20All\x20fields\x20are\
    \x20small\x20primitives\x20\xe2\x80\x94\x20keep\x20the\x20payload\x20tin\
    y\x20so\x20beacons\n\x20stay\x20cheap\x20at\x20fleet\x20scale\x20(many\
    \x20rooms\x20\xc3\x97\x200.2\x20Hz\x20cadence).\n\n\n\n\x03\x04\0\x01\
    \x12\x03\x0f\x08\x1a\n\x8c\x02\n\x03\x04\0\t\x12\x03\x14\x02\r\x1a\xff\
    \x01\x20Field\x201\x20previously\x20held\x20a\x20redundant\x20`room_id`\
    \x20string.\x20The\x20room\x20id\n\x20is\x20already\x20encoded\x20in\x20\
    the\x20NATS\x20subject\x20(`room.{room_id}.system`),\n\x20so\x20embeddin\
    g\x20a\x2036-byte\x20UUID\x20per\x20beacon\x20doubled\x20wire\x20size\
    \x20for\x20no\n\x20benefit.\x20Reserve\x20to\x20prevent\x20accidental\
    \x20reuse\x20(vc-4le).\n\n\x0b\n\x04\x04\0\t\0\x12\x03\x14\x0b\x0c\n\x0c\
    \n\x05\x04\0\t\0\x01\x12\x03\x14\x0b\x0c\n\x0c\n\x05\x04\0\t\0\x02\x12\
    \x03\x14\x0b\x0c\n\n\n\x03\x04\0\n\x12\x03\x15\x02\x15\n\x0b\n\x04\x04\0\
    \n\0\x12\x03\x15\x0b\x14\n\x8f\x01\n\x04\x04\0\x02\0\x12\x03\x19\x02\x1f\
    \x1a\x81\x01\x20Number\x20of\x20members\x20currently\x20tracked\x20in\
    \x20the\x20owner\x20pod's\x20RoomState\n\x20(senders\x20+\x20observers).\
    \x20Drives\x20the\x20participant\x20soft-cap\x20check.\n\n\x0c\n\x05\x04\
    \0\x02\0\x05\x12\x03\x19\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x19\
    \t\x1a\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x19\x1d\x1e\n\x96\x02\n\x04\
    \x04\0\x02\x01\x12\x03\x1f\x02\x15\x1a\x88\x02\x20Estimated\x20CPU\x20lo\
    ad\x20on\x20the\x20emitting\x20pod,\x20normalised\x20to\x20`[0,\x201]`.\
    \n\x20Currently\x20sourced\x20from\x20`/proc/loadavg`\x201-min\x20averag\
    e\x20divided\x20by\n\x20online\x20CPU\x20count\x20on\x20Linux;\x20falls\
    \x20back\x20to\x200.0\x20if\x20the\x20read\x20fails.\n\x200..1\x20is\x20\
    the\x20contract\x20the\x20consumer\x20relies\x20on\x20for\x20the\x20soft\
    -cap\x20check.\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x1f\x02\x07\n\x0c\
    \n\x05\x04\0\x02\x01\x01\x12\x03\x1f\x08\x10\n\x0c\n\x05\x04\0\x02\x01\
    \x03\x12\x03\x1f\x13\x14\n\xd9\x01\n\x04\x04\0\x02\x02\x12\x03$\x02\x1c\
    \x1a\xcb\x01\x20Owner\x20pod's\x20wall-clock\x20time\x20at\x20the\x20mom\
    ent\x20the\x20beacon\x20was\x20assembled,\n\x20expressed\x20as\x20UNIX\
    \x20milliseconds.\x20Lets\x20the\x20consumer\x20estimate\x20the\x20age\n\
    \x20of\x20a\x20beacon\x20against\x20its\x20own\x20clock\x20(and\x20detec\
    t\x20stalled\x20emitters).\n\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03$\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03$\t\x17\n\x0c\n\x05\x04\0\x02\
    \x02\x03\x12\x03$\x1a\x1bb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(HealthBeaconPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
