// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/media_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:MediaPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MediaPacket {
    // message fields
    // @@protoc_insertion_point(field:MediaPacket.media_type)
    pub media_type: ::protobuf::EnumOrUnknown<media_packet::MediaType>,
    // @@protoc_insertion_point(field:MediaPacket.user_id)
    pub user_id: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:MediaPacket.data)
    pub data: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:MediaPacket.frame_type)
    pub frame_type: ::std::string::String,
    // @@protoc_insertion_point(field:MediaPacket.timestamp)
    pub timestamp: f64,
    // @@protoc_insertion_point(field:MediaPacket.duration)
    pub duration: f64,
    // @@protoc_insertion_point(field:MediaPacket.audio_metadata)
    pub audio_metadata: ::protobuf::MessageField<AudioMetadata>,
    // @@protoc_insertion_point(field:MediaPacket.video_metadata)
    pub video_metadata: ::protobuf::MessageField<VideoMetadata>,
    // @@protoc_insertion_point(field:MediaPacket.heartbeat_metadata)
    pub heartbeat_metadata: ::protobuf::MessageField<HeartbeatMetadata>,
    // @@protoc_insertion_point(field:MediaPacket.routing_header)
    pub routing_header: ::protobuf::MessageField<RoutingHeader>,
    // special fields
    // @@protoc_insertion_point(special_field:MediaPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MediaPacket {
    fn default() -> &'a MediaPacket {
        <MediaPacket as ::protobuf::Message>::default_instance()
    }
}

impl MediaPacket {
    pub fn new() -> MediaPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(10);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "media_type",
            |m: &MediaPacket| { &m.media_type },
            |m: &mut MediaPacket| { &mut m.media_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "user_id",
            |m: &MediaPacket| { &m.user_id },
            |m: &mut MediaPacket| { &mut m.user_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &MediaPacket| { &m.data },
            |m: &mut MediaPacket| { &mut m.data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "frame_type",
            |m: &MediaPacket| { &m.frame_type },
            |m: &mut MediaPacket| { &mut m.frame_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "timestamp",
            |m: &MediaPacket| { &m.timestamp },
            |m: &mut MediaPacket| { &mut m.timestamp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "duration",
            |m: &MediaPacket| { &m.duration },
            |m: &mut MediaPacket| { &mut m.duration },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, AudioMetadata>(
            "audio_metadata",
            |m: &MediaPacket| { &m.audio_metadata },
            |m: &mut MediaPacket| { &mut m.audio_metadata },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, VideoMetadata>(
            "video_metadata",
            |m: &MediaPacket| { &m.video_metadata },
            |m: &mut MediaPacket| { &mut m.video_metadata },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, HeartbeatMetadata>(
            "heartbeat_metadata",
            |m: &MediaPacket| { &m.heartbeat_metadata },
            |m: &mut MediaPacket| { &mut m.heartbeat_metadata },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, RoutingHeader>(
            "routing_header",
            |m: &MediaPacket| { &m.routing_header },
            |m: &mut MediaPacket| { &mut m.routing_header },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MediaPacket>(
            "MediaPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MediaPacket {
    const NAME: &'static str = "MediaPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.media_type = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.user_id = is.read_bytes()?;
                },
                26 => {
                    self.data = is.read_bytes()?;
                },
                34 => {
                    self.frame_type = is.read_string()?;
                },
                41 => {
                    self.timestamp = is.read_double()?;
                },
                49 => {
                    self.duration = is.read_double()?;
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.audio_metadata)?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.video_metadata)?;
                },
                74 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.heartbeat_metadata)?;
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.routing_header)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.media_type != ::protobuf::EnumOrUnknown::new(media_packet::MediaType::MEDIA_TYPE_UNKNOWN) {
            my_size += ::protobuf::rt::int32_size(1, self.media_type.value());
        }
        if !self.user_id.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.user_id);
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.data);
        }
        if !self.frame_type.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.frame_type);
        }
        if self.timestamp != 0. {
            my_size += 1 + 8;
        }
        if self.duration != 0. {
            my_size += 1 + 8;
        }
        if let Some(v) = self.audio_metadata.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.video_metadata.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.heartbeat_metadata.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.routing_header.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.media_type != ::protobuf::EnumOrUnknown::new(media_packet::MediaType::MEDIA_TYPE_UNKNOWN) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.media_type))?;
        }
        if !self.user_id.is_empty() {
            os.write_bytes(2, &self.user_id)?;
        }
        if !self.data.is_empty() {
            os.write_bytes(3, &self.data)?;
        }
        if !self.frame_type.is_empty() {
            os.write_string(4, &self.frame_type)?;
        }
        if self.timestamp != 0. {
            os.write_double(5, self.timestamp)?;
        }
        if self.duration != 0. {
            os.write_double(6, self.duration)?;
        }
        if let Some(v) = self.audio_metadata.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.video_metadata.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if let Some(v) = self.heartbeat_metadata.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
        }
        if let Some(v) = self.routing_header.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MediaPacket {
        MediaPacket::new()
    }

    fn clear(&mut self) {
        self.media_type = ::protobuf::EnumOrUnknown::new(media_packet::MediaType::MEDIA_TYPE_UNKNOWN);
        self.user_id.clear();
        self.data.clear();
        self.frame_type.clear();
        self.timestamp = 0.;
        self.duration = 0.;
        self.audio_metadata.clear();
        self.video_metadata.clear();
        self.heartbeat_metadata.clear();
        self.routing_header.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MediaPacket {
        static instance: MediaPacket = MediaPacket {
            media_type: ::protobuf::EnumOrUnknown::from_i32(0),
            user_id: ::std::vec::Vec::new(),
            data: ::std::vec::Vec::new(),
            frame_type: ::std::string::String::new(),
            timestamp: 0.,
            duration: 0.,
            audio_metadata: ::protobuf::MessageField::none(),
            video_metadata: ::protobuf::MessageField::none(),
            heartbeat_metadata: ::protobuf::MessageField::none(),
            routing_header: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MediaPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MediaPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MediaPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MediaPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `MediaPacket`
pub mod media_packet {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:MediaPacket.MediaType)
    pub enum MediaType {
        // @@protoc_insertion_point(enum_value:MediaPacket.MediaType.MEDIA_TYPE_UNKNOWN)
        MEDIA_TYPE_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:MediaPacket.MediaType.VIDEO)
        VIDEO = 1,
        // @@protoc_insertion_point(enum_value:MediaPacket.MediaType.AUDIO)
        AUDIO = 2,
        // @@protoc_insertion_point(enum_value:MediaPacket.MediaType.SCREEN)
        SCREEN = 3,
        // @@protoc_insertion_point(enum_value:MediaPacket.MediaType.HEARTBEAT)
        HEARTBEAT = 4,
        // @@protoc_insertion_point(enum_value:MediaPacket.MediaType.RTT)
        RTT = 5,
        // @@protoc_insertion_point(enum_value:MediaPacket.MediaType.KEYFRAME_REQUEST)
        KEYFRAME_REQUEST = 6,
    }

    impl ::protobuf::Enum for MediaType {
        const NAME: &'static str = "MediaType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<MediaType> {
            match value {
                0 => ::std::option::Option::Some(MediaType::MEDIA_TYPE_UNKNOWN),
                1 => ::std::option::Option::Some(MediaType::VIDEO),
                2 => ::std::option::Option::Some(MediaType::AUDIO),
                3 => ::std::option::Option::Some(MediaType::SCREEN),
                4 => ::std::option::Option::Some(MediaType::HEARTBEAT),
                5 => ::std::option::Option::Some(MediaType::RTT),
                6 => ::std::option::Option::Some(MediaType::KEYFRAME_REQUEST),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<MediaType> {
            match str {
                "MEDIA_TYPE_UNKNOWN" => ::std::option::Option::Some(MediaType::MEDIA_TYPE_UNKNOWN),
                "VIDEO" => ::std::option::Option::Some(MediaType::VIDEO),
                "AUDIO" => ::std::option::Option::Some(MediaType::AUDIO),
                "SCREEN" => ::std::option::Option::Some(MediaType::SCREEN),
                "HEARTBEAT" => ::std::option::Option::Some(MediaType::HEARTBEAT),
                "RTT" => ::std::option::Option::Some(MediaType::RTT),
                "KEYFRAME_REQUEST" => ::std::option::Option::Some(MediaType::KEYFRAME_REQUEST),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [MediaType] = &[
            MediaType::MEDIA_TYPE_UNKNOWN,
            MediaType::VIDEO,
            MediaType::AUDIO,
            MediaType::SCREEN,
            MediaType::HEARTBEAT,
            MediaType::RTT,
            MediaType::KEYFRAME_REQUEST,
        ];
    }

    impl ::protobuf::EnumFull for MediaType {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("MediaPacket.MediaType").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for MediaType {
        fn default() -> Self {
            MediaType::MEDIA_TYPE_UNKNOWN
        }
    }

    impl MediaType {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<MediaType>("MediaPacket.MediaType")
        }
    }
}

// @@protoc_insertion_point(message:RoutingHeader)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RoutingHeader {
    // message fields
    // @@protoc_insertion_point(field:RoutingHeader.is_keyframe)
    pub is_keyframe: bool,
    // @@protoc_insertion_point(field:RoutingHeader.temporal_layer_id)
    pub temporal_layer_id: u32,
    // @@protoc_insertion_point(field:RoutingHeader.spatial_layer_id)
    pub spatial_layer_id: u32,
    // @@protoc_insertion_point(field:RoutingHeader.audio_level)
    pub audio_level: f32,
    // @@protoc_insertion_point(field:RoutingHeader.is_speaking)
    pub is_speaking: bool,
    // @@protoc_insertion_point(field:RoutingHeader.frame_marker)
    pub frame_marker: u32,
    // @@protoc_insertion_point(field:RoutingHeader.picture_id)
    pub picture_id: u64,
    // special fields
    // @@protoc_insertion_point(special_field:RoutingHeader.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RoutingHeader {
    fn default() -> &'a RoutingHeader {
        <RoutingHeader as ::protobuf::Message>::default_instance()
    }
}

impl RoutingHeader {
    pub fn new() -> RoutingHeader {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_keyframe",
            |m: &RoutingHeader| { &m.is_keyframe },
            |m: &mut RoutingHeader| { &mut m.is_keyframe },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "temporal_layer_id",
            |m: &RoutingHeader| { &m.temporal_layer_id },
            |m: &mut RoutingHeader| { &mut m.temporal_layer_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "spatial_layer_id",
            |m: &RoutingHeader| { &m.spatial_layer_id },
            |m: &mut RoutingHeader| { &mut m.spatial_layer_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "audio_level",
            |m: &RoutingHeader| { &m.audio_level },
            |m: &mut RoutingHeader| { &mut m.audio_level },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_speaking",
            |m: &RoutingHeader| { &m.is_speaking },
            |m: &mut RoutingHeader| { &mut m.is_speaking },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "frame_marker",
            |m: &RoutingHeader| { &m.frame_marker },
            |m: &mut RoutingHeader| { &mut m.frame_marker },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "picture_id",
            |m: &RoutingHeader| { &m.picture_id },
            |m: &mut RoutingHeader| { &mut m.picture_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RoutingHeader>(
            "RoutingHeader",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RoutingHeader {
    const NAME: &'static str = "RoutingHeader";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.is_keyframe = is.read_bool()?;
                },
                16 => {
                    self.temporal_layer_id = is.read_uint32()?;
                },
                24 => {
                    self.spatial_layer_id = is.read_uint32()?;
                },
                37 => {
                    self.audio_level = is.read_float()?;
                },
                40 => {
                    self.is_speaking = is.read_bool()?;
                },
                48 => {
                    self.frame_marker = is.read_uint32()?;
                },
                56 => {
                    self.picture_id = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.is_keyframe != false {
            my_size += 1 + 1;
        }
        if self.temporal_layer_id != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.temporal_layer_id);
        }
        if self.spatial_layer_id != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.spatial_layer_id);
        }
        if self.audio_level != 0. {
            my_size += 1 + 4;
        }
        if self.is_speaking != false {
            my_size += 1 + 1;
        }
        if self.frame_marker != 0 {
            my_size += ::protobuf::rt::uint32_size(6, self.frame_marker);
        }
        if self.picture_id != 0 {
            my_size += ::protobuf::rt::uint64_size(7, self.picture_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.is_keyframe != false {
            os.write_bool(1, self.is_keyframe)?;
        }
        if self.temporal_layer_id != 0 {
            os.write_uint32(2, self.temporal_layer_id)?;
        }
        if self.spatial_layer_id != 0 {
            os.write_uint32(3, self.spatial_layer_id)?;
        }
        if self.audio_level != 0. {
            os.write_float(4, self.audio_level)?;
        }
        if self.is_speaking != false {
            os.write_bool(5, self.is_speaking)?;
        }
        if self.frame_marker != 0 {
            os.write_uint32(6, self.frame_marker)?;
        }
        if self.picture_id != 0 {
            os.write_uint64(7, self.picture_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RoutingHeader {
        RoutingHeader::new()
    }

    fn clear(&mut self) {
        self.is_keyframe = false;
        self.temporal_layer_id = 0;
        self.spatial_layer_id = 0;
        self.audio_level = 0.;
        self.is_speaking = false;
        self.frame_marker = 0;
        self.picture_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RoutingHeader {
        static instance: RoutingHeader = RoutingHeader {
            is_keyframe: false,
            temporal_layer_id: 0,
            spatial_layer_id: 0,
            audio_level: 0.,
            is_speaking: false,
            frame_marker: 0,
            picture_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RoutingHeader {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RoutingHeader").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RoutingHeader {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RoutingHeader {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:AudioMetadata)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AudioMetadata {
    // message fields
    // @@protoc_insertion_point(field:AudioMetadata.audio_format)
    pub audio_format: ::std::string::String,
    // @@protoc_insertion_point(field:AudioMetadata.audio_number_of_channels)
    pub audio_number_of_channels: u32,
    // @@protoc_insertion_point(field:AudioMetadata.audio_number_of_frames)
    pub audio_number_of_frames: u32,
    // @@protoc_insertion_point(field:AudioMetadata.audio_sample_rate)
    pub audio_sample_rate: f32,
    // @@protoc_insertion_point(field:AudioMetadata.sequence)
    pub sequence: u64,
    // special fields
    // @@protoc_insertion_point(special_field:AudioMetadata.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AudioMetadata {
    fn default() -> &'a AudioMetadata {
        <AudioMetadata as ::protobuf::Message>::default_instance()
    }
}

impl AudioMetadata {
    pub fn new() -> AudioMetadata {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "audio_format",
            |m: &AudioMetadata| { &m.audio_format },
            |m: &mut AudioMetadata| { &mut m.audio_format },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "audio_number_of_channels",
            |m: &AudioMetadata| { &m.audio_number_of_channels },
            |m: &mut AudioMetadata| { &mut m.audio_number_of_channels },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "audio_number_of_frames",
            |m: &AudioMetadata| { &m.audio_number_of_frames },
            |m: &mut AudioMetadata| { &mut m.audio_number_of_frames },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "audio_sample_rate",
            |m: &AudioMetadata| { &m.audio_sample_rate },
            |m: &mut AudioMetadata| { &mut m.audio_sample_rate },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sequence",
            |m: &AudioMetadata| { &m.sequence },
            |m: &mut AudioMetadata| { &mut m.sequence },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AudioMetadata>(
            "AudioMetadata",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AudioMetadata {
    const NAME: &'static str = "AudioMetadata";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.audio_format = is.read_string()?;
                },
                16 => {
                    self.audio_number_of_channels = is.read_uint32()?;
                },
                24 => {
                    self.audio_number_of_frames = is.read_uint32()?;
                },
                37 => {
                    self.audio_sample_rate = is.read_float()?;
                },
                40 => {
                    self.sequence = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.audio_format.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.audio_format);
        }
        if self.audio_number_of_channels != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.audio_number_of_channels);
        }
        if self.audio_number_of_frames != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.audio_number_of_frames);
        }
        if self.audio_sample_rate != 0. {
            my_size += 1 + 4;
        }
        if self.sequence != 0 {
            my_size += ::protobuf::rt::uint64_size(5, self.sequence);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.audio_format.is_empty() {
            os.write_string(1, &self.audio_format)?;
        }
        if self.audio_number_of_channels != 0 {
            os.write_uint32(2, self.audio_number_of_channels)?;
        }
        if self.audio_number_of_frames != 0 {
            os.write_uint32(3, self.audio_number_of_frames)?;
        }
        if self.audio_sample_rate != 0. {
            os.write_float(4, self.audio_sample_rate)?;
        }
        if self.sequence != 0 {
            os.write_uint64(5, self.sequence)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AudioMetadata {
        AudioMetadata::new()
    }

    fn clear(&mut self) {
        self.audio_format.clear();
        self.audio_number_of_channels = 0;
        self.audio_number_of_frames = 0;
        self.audio_sample_rate = 0.;
        self.sequence = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AudioMetadata {
        static instance: AudioMetadata = AudioMetadata {
            audio_format: ::std::string::String::new(),
            audio_number_of_channels: 0,
            audio_number_of_frames: 0,
            audio_sample_rate: 0.,
            sequence: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AudioMetadata {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AudioMetadata").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AudioMetadata {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AudioMetadata {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:VideoMetadata)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct VideoMetadata {
    // message fields
    // @@protoc_insertion_point(field:VideoMetadata.sequence)
    pub sequence: u64,
    // @@protoc_insertion_point(field:VideoMetadata.codec)
    pub codec: ::protobuf::EnumOrUnknown<VideoCodec>,
    // special fields
    // @@protoc_insertion_point(special_field:VideoMetadata.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VideoMetadata {
    fn default() -> &'a VideoMetadata {
        <VideoMetadata as ::protobuf::Message>::default_instance()
    }
}

impl VideoMetadata {
    pub fn new() -> VideoMetadata {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sequence",
            |m: &VideoMetadata| { &m.sequence },
            |m: &mut VideoMetadata| { &mut m.sequence },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "codec",
            |m: &VideoMetadata| { &m.codec },
            |m: &mut VideoMetadata| { &mut m.codec },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<VideoMetadata>(
            "VideoMetadata",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for VideoMetadata {
    const NAME: &'static str = "VideoMetadata";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.sequence = is.read_uint64()?;
                },
                16 => {
                    self.codec = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.sequence != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.sequence);
        }
        if self.codec != ::protobuf::EnumOrUnknown::new(VideoCodec::VIDEO_CODEC_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(2, self.codec.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.sequence != 0 {
            os.write_uint64(1, self.sequence)?;
        }
        if self.codec != ::protobuf::EnumOrUnknown::new(VideoCodec::VIDEO_CODEC_UNSPECIFIED) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.codec))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VideoMetadata {
        VideoMetadata::new()
    }

    fn clear(&mut self) {
        self.sequence = 0;
        self.codec = ::protobuf::EnumOrUnknown::new(VideoCodec::VIDEO_CODEC_UNSPECIFIED);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VideoMetadata {
        static instance: VideoMetadata = VideoMetadata {
            sequence: 0,
            codec: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for VideoMetadata {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("VideoMetadata").unwrap()).clone()
    }
}

impl ::std::fmt::Display for VideoMetadata {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VideoMetadata {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:HeartbeatMetadata)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HeartbeatMetadata {
    // message fields
    // @@protoc_insertion_point(field:HeartbeatMetadata.video_enabled)
    pub video_enabled: bool,
    // @@protoc_insertion_point(field:HeartbeatMetadata.audio_enabled)
    pub audio_enabled: bool,
    // @@protoc_insertion_point(field:HeartbeatMetadata.screen_enabled)
    pub screen_enabled: bool,
    // @@protoc_insertion_point(field:HeartbeatMetadata.is_speaking)
    pub is_speaking: bool,
    // special fields
    // @@protoc_insertion_point(special_field:HeartbeatMetadata.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HeartbeatMetadata {
    fn default() -> &'a HeartbeatMetadata {
        <HeartbeatMetadata as ::protobuf::Message>::default_instance()
    }
}

impl HeartbeatMetadata {
    pub fn new() -> HeartbeatMetadata {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "video_enabled",
            |m: &HeartbeatMetadata| { &m.video_enabled },
            |m: &mut HeartbeatMetadata| { &mut m.video_enabled },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "audio_enabled",
            |m: &HeartbeatMetadata| { &m.audio_enabled },
            |m: &mut HeartbeatMetadata| { &mut m.audio_enabled },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "screen_enabled",
            |m: &HeartbeatMetadata| { &m.screen_enabled },
            |m: &mut HeartbeatMetadata| { &mut m.screen_enabled },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_speaking",
            |m: &HeartbeatMetadata| { &m.is_speaking },
            |m: &mut HeartbeatMetadata| { &mut m.is_speaking },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<HeartbeatMetadata>(
            "HeartbeatMetadata",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for HeartbeatMetadata {
    const NAME: &'static str = "HeartbeatMetadata";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.video_enabled = is.read_bool()?;
                },
                16 => {
                    self.audio_enabled = is.read_bool()?;
                },
                24 => {
                    self.screen_enabled = is.read_bool()?;
                },
                32 => {
                    self.is_speaking = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.video_enabled != false {
            my_size += 1 + 1;
        }
        if self.audio_enabled != false {
            my_size += 1 + 1;
        }
        if self.screen_enabled != false {
            my_size += 1 + 1;
        }
        if self.is_speaking != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.video_enabled != false {
            os.write_bool(1, self.video_enabled)?;
        }
        if self.audio_enabled != false {
            os.write_bool(2, self.audio_enabled)?;
        }
        if self.screen_enabled != false {
            os.write_bool(3, self.screen_enabled)?;
        }
        if self.is_speaking != false {
            os.write_bool(4, self.is_speaking)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HeartbeatMetadata {
        HeartbeatMetadata::new()
    }

    fn clear(&mut self) {
        self.video_enabled = false;
        self.audio_enabled = false;
        self.screen_enabled = false;
        self.is_speaking = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HeartbeatMetadata {
        static instance: HeartbeatMetadata = HeartbeatMetadata {
            video_enabled: false,
            audio_enabled: false,
            screen_enabled: false,
            is_speaking: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for HeartbeatMetadata {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("HeartbeatMetadata").unwrap()).clone()
    }
}

impl ::std::fmt::Display for HeartbeatMetadata {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HeartbeatMetadata {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Video codec enum with profile/level details for scalability.
///  Format follows WebCodecs codec string conventions where applicable.
#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:VideoCodec)
pub enum VideoCodec {
    // @@protoc_insertion_point(enum_value:VideoCodec.VIDEO_CODEC_UNSPECIFIED)
    VIDEO_CODEC_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:VideoCodec.VP8)
    VP8 = 1,
    // @@protoc_insertion_point(enum_value:VideoCodec.VP9_PROFILE0_LEVEL10_8BIT)
    VP9_PROFILE0_LEVEL10_8BIT = 2,
}

impl ::protobuf::Enum for VideoCodec {
    const NAME: &'static str = "VideoCodec";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<VideoCodec> {
        match value {
            0 => ::std::option::Option::Some(VideoCodec::VIDEO_CODEC_UNSPECIFIED),
            1 => ::std::option::Option::Some(VideoCodec::VP8),
            2 => ::std::option::Option::Some(VideoCodec::VP9_PROFILE0_LEVEL10_8BIT),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<VideoCodec> {
        match str {
            "VIDEO_CODEC_UNSPECIFIED" => ::std::option::Option::Some(VideoCodec::VIDEO_CODEC_UNSPECIFIED),
            "VP8" => ::std::option::Option::Some(VideoCodec::VP8),
            "VP9_PROFILE0_LEVEL10_8BIT" => ::std::option::Option::Some(VideoCodec::VP9_PROFILE0_LEVEL10_8BIT),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [VideoCodec] = &[
        VideoCodec::VIDEO_CODEC_UNSPECIFIED,
        VideoCodec::VP8,
        VideoCodec::VP9_PROFILE0_LEVEL10_8BIT,
    ];
}

impl ::protobuf::EnumFull for VideoCodec {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("VideoCodec").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for VideoCodec {
    fn default() -> Self {
        VideoCodec::VIDEO_CODEC_UNSPECIFIED
    }
}

impl VideoCodec {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<VideoCodec>("VideoCodec")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18types/media_packet.proto\"\xbf\x04\n\x0bMediaPacket\x125\n\nmedia_\
    type\x18\x01\x20\x01(\x0e2\x16.MediaPacket.MediaTypeR\tmediaType\x12\x17\
    \n\x07user_id\x18\x02\x20\x01(\x0cR\x06userId\x12\x12\n\x04data\x18\x03\
    \x20\x01(\x0cR\x04data\x12\x1d\n\nframe_type\x18\x04\x20\x01(\tR\tframeT\
    ype\x12\x1c\n\ttimestamp\x18\x05\x20\x01(\x01R\ttimestamp\x12\x1a\n\x08d\
    uration\x18\x06\x20\x01(\x01R\x08duration\x125\n\x0eaudio_metadata\x18\
    \x07\x20\x01(\x0b2\x0e.AudioMetadataR\raudioMetadata\x125\n\x0evideo_met\
    adata\x18\x08\x20\x01(\x0b2\x0e.VideoMetadataR\rvideoMetadata\x12A\n\x12\
    heartbeat_metadata\x18\t\x20\x01(\x0b2\x12.HeartbeatMetadataR\x11heartbe\
    atMetadata\x12:\n\x0erouting_header\x18\n\x20\x01(\x0b2\x0e.RoutingHeade\
    rH\0R\rroutingHeader\x88\x01\x01\"s\n\tMediaType\x12\x16\n\x12MEDIA_TYPE\
    _UNKNOWN\x10\0\x12\t\n\x05VIDEO\x10\x01\x12\t\n\x05AUDIO\x10\x02\x12\n\n\
    \x06SCREEN\x10\x03\x12\r\n\tHEARTBEAT\x10\x04\x12\x07\n\x03RTT\x10\x05\
    \x12\x14\n\x10KEYFRAME_REQUEST\x10\x06B\x11\n\x0f_routing_header\"\x8a\
    \x02\n\rRoutingHeader\x12\x1f\n\x0bis_keyframe\x18\x01\x20\x01(\x08R\nis\
    Keyframe\x12*\n\x11temporal_layer_id\x18\x02\x20\x01(\rR\x0ftemporalLaye\
    rId\x12(\n\x10spatial_layer_id\x18\x03\x20\x01(\rR\x0espatialLayerId\x12\
    \x1f\n\x0baudio_level\x18\x04\x20\x01(\x02R\naudioLevel\x12\x1f\n\x0bis_\
    speaking\x18\x05\x20\x01(\x08R\nisSpeaking\x12!\n\x0cframe_marker\x18\
    \x06\x20\x01(\rR\x0bframeMarker\x12\x1d\n\npicture_id\x18\x07\x20\x01(\
    \x04R\tpictureId\"\xe8\x01\n\rAudioMetadata\x12!\n\x0caudio_format\x18\
    \x01\x20\x01(\tR\x0baudioFormat\x127\n\x18audio_number_of_channels\x18\
    \x02\x20\x01(\rR\x15audioNumberOfChannels\x123\n\x16audio_number_of_fram\
    es\x18\x03\x20\x01(\rR\x13audioNumberOfFrames\x12*\n\x11audio_sample_rat\
    e\x18\x04\x20\x01(\x02R\x0faudioSampleRate\x12\x1a\n\x08sequence\x18\x05\
    \x20\x01(\x04R\x08sequence\"N\n\rVideoMetadata\x12\x1a\n\x08sequence\x18\
    \x01\x20\x01(\x04R\x08sequence\x12!\n\x05codec\x18\x02\x20\x01(\x0e2\x0b\
    .VideoCodecR\x05codec\"\xa5\x01\n\x11HeartbeatMetadata\x12#\n\rvideo_ena\
    bled\x18\x01\x20\x01(\x08R\x0cvideoEnabled\x12#\n\raudio_enabled\x18\x02\
    \x20\x01(\x08R\x0caudioEnabled\x12%\n\x0escreen_enabled\x18\x03\x20\x01(\
    \x08R\rscreenEnabled\x12\x1f\n\x0bis_speaking\x18\x04\x20\x01(\x08R\nisS\
    peaking*Q\n\nVideoCodec\x12\x1b\n\x17VIDEO_CODEC_UNSPECIFIED\x10\0\x12\
    \x07\n\x03VP8\x10\x01\x12\x1d\n\x19VP9_PROFILE0_LEVEL10_8BIT\x10\x02J\
    \xdc\x15\n\x06\x12\x04\0\0H\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\n\n\
    \x02\x04\0\x12\x04\x02\0\x16\x01\n\n\n\x03\x04\0\x01\x12\x03\x02\x08\x13\
    \n\x0c\n\x04\x04\0\x04\0\x12\x04\x03\x02\x0b\x03\n\x0c\n\x05\x04\0\x04\0\
    \x01\x12\x03\x03\x07\x10\n\r\n\x06\x04\0\x04\0\x02\0\x12\x03\x04\x04\x1b\
    \n\x0e\n\x07\x04\0\x04\0\x02\0\x01\x12\x03\x04\x04\x16\n\x0e\n\x07\x04\0\
    \x04\0\x02\0\x02\x12\x03\x04\x19\x1a\n\r\n\x06\x04\0\x04\0\x02\x01\x12\
    \x03\x05\x04\x0e\n\x0e\n\x07\x04\0\x04\0\x02\x01\x01\x12\x03\x05\x04\t\n\
    \x0e\n\x07\x04\0\x04\0\x02\x01\x02\x12\x03\x05\x0c\r\n\r\n\x06\x04\0\x04\
    \0\x02\x02\x12\x03\x06\x04\x0e\n\x0e\n\x07\x04\0\x04\0\x02\x02\x01\x12\
    \x03\x06\x04\t\n\x0e\n\x07\x04\0\x04\0\x02\x02\x02\x12\x03\x06\x0c\r\n\r\
    \n\x06\x04\0\x04\0\x02\x03\x12\x03\x07\x04\x0f\n\x0e\n\x07\x04\0\x04\0\
    \x02\x03\x01\x12\x03\x07\x04\n\n\x0e\n\x07\x04\0\x04\0\x02\x03\x02\x12\
    \x03\x07\r\x0e\n\r\n\x06\x04\0\x04\0\x02\x04\x12\x03\x08\x04\x12\n\x0e\n\
    \x07\x04\0\x04\0\x02\x04\x01\x12\x03\x08\x04\r\n\x0e\n\x07\x04\0\x04\0\
    \x02\x04\x02\x12\x03\x08\x10\x11\n%\n\x06\x04\0\x04\0\x02\x05\x12\x03\t\
    \x04\x0c\"\x16\x20Client\x20to\x20Server\x20RTT\n\n\x0e\n\x07\x04\0\x04\
    \0\x02\x05\x01\x12\x03\t\x04\x07\n\x0e\n\x07\x04\0\x04\0\x02\x05\x02\x12\
    \x03\t\n\x0b\n3\n\x06\x04\0\x04\0\x02\x06\x12\x03\n\x04\x19\"$\x20Reques\
    t\x20keyframe\x20from\x20sender\x20(PLI)\n\n\x0e\n\x07\x04\0\x04\0\x02\
    \x06\x01\x12\x03\n\x04\x14\n\x0e\n\x07\x04\0\x04\0\x02\x06\x02\x12\x03\n\
    \x17\x18\n\x0b\n\x04\x04\0\x02\0\x12\x03\x0c\x02\x1b\n\x0c\n\x05\x04\0\
    \x02\0\x06\x12\x03\x0c\x02\x0b\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x0c\
    \x0c\x16\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0c\x19\x1a\n\x0b\n\x04\x04\
    \0\x02\x01\x12\x03\r\x02\x14\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\r\x02\
    \x07\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\r\x08\x0f\n\x0c\n\x05\x04\0\
    \x02\x01\x03\x12\x03\r\x12\x13\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x0e\x02\
    \x11\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x0e\x02\x07\n\x0c\n\x05\x04\0\
    \x02\x02\x01\x12\x03\x0e\x08\x0c\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\
    \x0e\x0f\x10\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x0f\x02\x18\n\x0c\n\x05\
    \x04\0\x02\x03\x05\x12\x03\x0f\x02\x08\n\x0c\n\x05\x04\0\x02\x03\x01\x12\
    \x03\x0f\t\x13\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x0f\x16\x17\n\x0b\n\
    \x04\x04\0\x02\x04\x12\x03\x10\x02\x17\n\x0c\n\x05\x04\0\x02\x04\x05\x12\
    \x03\x10\x02\x08\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\x10\t\x12\n\x0c\n\
    \x05\x04\0\x02\x04\x03\x12\x03\x10\x15\x16\n\x0b\n\x04\x04\0\x02\x05\x12\
    \x03\x11\x02\x16\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\x11\x02\x08\n\x0c\
    \n\x05\x04\0\x02\x05\x01\x12\x03\x11\t\x11\n\x0c\n\x05\x04\0\x02\x05\x03\
    \x12\x03\x11\x14\x15\n\x0b\n\x04\x04\0\x02\x06\x12\x03\x12\x02#\n\x0c\n\
    \x05\x04\0\x02\x06\x06\x12\x03\x12\x02\x0f\n\x0c\n\x05\x04\0\x02\x06\x01\
    \x12\x03\x12\x10\x1e\n\x0c\n\x05\x04\0\x02\x06\x03\x12\x03\x12!\"\n\x0b\
    \n\x04\x04\0\x02\x07\x12\x03\x13\x02#\n\x0c\n\x05\x04\0\x02\x07\x06\x12\
    \x03\x13\x02\x0f\n\x0c\n\x05\x04\0\x02\x07\x01\x12\x03\x13\x10\x1e\n\x0c\
    \n\x05\x04\0\x02\x07\x03\x12\x03\x13!\"\n\x0b\n\x04\x04\0\x02\x08\x12\
    \x03\x14\x02+\n\x0c\n\x05\x04\0\x02\x08\x06\x12\x03\x14\x02\x13\n\x0c\n\
    \x05\x04\0\x02\x08\x01\x12\x03\x14\x14&\n\x0c\n\x05\x04\0\x02\x08\x03\
    \x12\x03\x14)*\n\x0b\n\x04\x04\0\x02\t\x12\x03\x15\x02-\n\x0c\n\x05\x04\
    \0\x02\t\x04\x12\x03\x15\x02\n\n\x0c\n\x05\x04\0\x02\t\x06\x12\x03\x15\
    \x0b\x18\n\x0c\n\x05\x04\0\x02\t\x01\x12\x03\x15\x19'\n\x0c\n\x05\x04\0\
    \x02\t\x03\x12\x03\x15*,\n\n\n\x02\x04\x01\x12\x04\x18\0\x20\x01\n\n\n\
    \x03\x04\x01\x01\x12\x03\x18\x08\x15\n\x0b\n\x04\x04\x01\x02\0\x12\x03\
    \x19\x02\x17\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\x19\x02\x06\n\x0c\n\
    \x05\x04\x01\x02\0\x01\x12\x03\x19\x07\x12\n\x0c\n\x05\x04\x01\x02\0\x03\
    \x12\x03\x19\x15\x16\n'\n\x04\x04\x01\x02\x01\x12\x03\x1a\x02\x1f\"\x1a\
    \x200=base,\x201..N=enhancement\n\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\
    \x03\x1a\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\x1a\t\x1a\n\x0c\
    \n\x05\x04\x01\x02\x01\x03\x12\x03\x1a\x1d\x1e\n'\n\x04\x04\x01\x02\x02\
    \x12\x03\x1b\x02\x1e\"\x1a\x200=base,\x201..N=enhancement\n\n\x0c\n\x05\
    \x04\x01\x02\x02\x05\x12\x03\x1b\x02\x08\n\x0c\n\x05\x04\x01\x02\x02\x01\
    \x12\x03\x1b\t\x19\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x1b\x1c\x1d\n\
    #\n\x04\x04\x01\x02\x03\x12\x03\x1c\x02\x18\"\x16\x200..1\x20RMS,\x20AUD\
    IO\x20only\n\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\x03\x1c\x02\x07\n\x0c\n\
    \x05\x04\x01\x02\x03\x01\x12\x03\x1c\x08\x13\n\x0c\n\x05\x04\x01\x02\x03\
    \x03\x12\x03\x1c\x16\x17\n!\n\x04\x04\x01\x02\x04\x12\x03\x1d\x02\x17\"\
    \x14\x20VAD/threshold\x20hint\n\n\x0c\n\x05\x04\x01\x02\x04\x05\x12\x03\
    \x1d\x02\x06\n\x0c\n\x05\x04\x01\x02\x04\x01\x12\x03\x1d\x07\x12\n\x0c\n\
    \x05\x04\x01\x02\x04\x03\x12\x03\x1d\x15\x16\nJ\n\x04\x04\x01\x02\x05\
    \x12\x03\x1e\x02\x1a\"=\x20bitfield:\x20START_OF_FRAME=1,\x20END_OF_FRAM\
    E=2,\x20REFERENCES_T0=4\n\n\x0c\n\x05\x04\x01\x02\x05\x05\x12\x03\x1e\
    \x02\x08\n\x0c\n\x05\x04\x01\x02\x05\x01\x12\x03\x1e\t\x15\n\x0c\n\x05\
    \x04\x01\x02\x05\x03\x12\x03\x1e\x18\x19\n*\n\x04\x04\x01\x02\x06\x12\
    \x03\x1f\x02\x18\"\x1d\x20for\x20SVC\x20dependency\x20tracking\n\n\x0c\n\
    \x05\x04\x01\x02\x06\x05\x12\x03\x1f\x02\x08\n\x0c\n\x05\x04\x01\x02\x06\
    \x01\x12\x03\x1f\t\x13\n\x0c\n\x05\x04\x01\x02\x06\x03\x12\x03\x1f\x16\
    \x17\n\n\n\x02\x04\x02\x12\x04\"\0(\x01\n\n\n\x03\x04\x02\x01\x12\x03\"\
    \x08\x15\n\x0b\n\x04\x04\x02\x02\0\x12\x03#\x02\x1a\n\x0c\n\x05\x04\x02\
    \x02\0\x05\x12\x03#\x02\x08\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03#\t\x15\
    \n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03#\x18\x19\n\x0b\n\x04\x04\x02\x02\
    \x01\x12\x03$\x02&\n\x0c\n\x05\x04\x02\x02\x01\x05\x12\x03$\x02\x08\n\
    \x0c\n\x05\x04\x02\x02\x01\x01\x12\x03$\t!\n\x0c\n\x05\x04\x02\x02\x01\
    \x03\x12\x03$$%\n\x0b\n\x04\x04\x02\x02\x02\x12\x03%\x02$\n\x0c\n\x05\
    \x04\x02\x02\x02\x05\x12\x03%\x02\x08\n\x0c\n\x05\x04\x02\x02\x02\x01\
    \x12\x03%\t\x1f\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03%\"#\n\x0b\n\x04\
    \x04\x02\x02\x03\x12\x03&\x02\x1e\n\x0c\n\x05\x04\x02\x02\x03\x05\x12\
    \x03&\x02\x07\n\x0c\n\x05\x04\x02\x02\x03\x01\x12\x03&\x08\x19\n\x0c\n\
    \x05\x04\x02\x02\x03\x03\x12\x03&\x1c\x1d\n\x0b\n\x04\x04\x02\x02\x04\
    \x12\x03'\x02\x16\n\x0c\n\x05\x04\x02\x02\x04\x05\x12\x03'\x02\x08\n\x0c\
    \n\x05\x04\x02\x02\x04\x01\x12\x03'\t\x11\n\x0c\n\x05\x04\x02\x02\x04\
    \x03\x12\x03'\x14\x15\n\n\n\x02\x04\x03\x12\x04*\0-\x01\n\n\n\x03\x04\
    \x03\x01\x12\x03*\x08\x15\n\x0b\n\x04\x04\x03\x02\0\x12\x03+\x02\x16\n\
    \x0c\n\x05\x04\x03\x02\0\x05\x12\x03+\x02\x08\n\x0c\n\x05\x04\x03\x02\0\
    \x01\x12\x03+\t\x11\n\x0c\n\x05\x04\x03\x02\0\x03\x12\x03+\x14\x15\n\x0b\
    \n\x04\x04\x03\x02\x01\x12\x03,\x02\x17\n\x0c\n\x05\x04\x03\x02\x01\x06\
    \x12\x03,\x02\x0c\n\x0c\n\x05\x04\x03\x02\x01\x01\x12\x03,\r\x12\n\x0c\n\
    \x05\x04\x03\x02\x01\x03\x12\x03,\x15\x16\n\x90\x01\n\x02\x05\0\x12\x041\
    \0A\x01\x1a\x83\x01\x20Video\x20codec\x20enum\x20with\x20profile/level\
    \x20details\x20for\x20scalability.\n\x20Format\x20follows\x20WebCodecs\
    \x20codec\x20string\x20conventions\x20where\x20applicable.\n\n\n\n\x03\
    \x05\0\x01\x12\x031\x05\x0f\n=\n\x04\x05\0\x02\0\x12\x032\x02\x1e\"0\x20\
    Default\x20-\x20skip\x20decoding\x20if\x20codec\x20not\x20specified\n\n\
    \x0c\n\x05\x05\0\x02\0\x01\x12\x032\x02\x19\n\x0c\n\x05\x05\0\x02\0\x02\
    \x12\x032\x1c\x1d\n.\n\x04\x05\0\x02\x01\x12\x035\x02\n\x1a!\x20VP8\x20-\
    \x20no\x20profile/level\x20variants\n\n\x0c\n\x05\x05\0\x02\x01\x01\x12\
    \x035\x02\x05\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x035\x08\t\nu\n\x04\x05\
    \0\x02\x02\x12\x038\x02\x20\x1a9\x20VP9\x20profiles:\x20vp09.PP.LL.DD\
    \x20(Profile,\x20Level,\x20bit\x20Depth)\n\"-\x20vp09.00.10.08\x20-\x20P\
    rofile\x200,\x20Level\x201.0,\x208-bit\n\n\x0c\n\x05\x05\0\x02\x02\x01\
    \x12\x038\x02\x1b\n\x0c\n\x05\x05\0\x02\x02\x02\x12\x038\x1e\x1f\n\n\n\
    \x02\x04\x04\x12\x04C\0H\x01\n\n\n\x03\x04\x04\x01\x12\x03C\x08\x19\n\
    \x0b\n\x04\x04\x04\x02\0\x12\x03D\x02\x19\n\x0c\n\x05\x04\x04\x02\0\x05\
    \x12\x03D\x02\x06\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x03D\x07\x14\n\x0c\n\
    \x05\x04\x04\x02\0\x03\x12\x03D\x17\x18\n\x0b\n\x04\x04\x04\x02\x01\x12\
    \x03E\x02\x19\n\x0c\n\x05\x04\x04\x02\x01\x05\x12\x03E\x02\x06\n\x0c\n\
    \x05\x04\x04\x02\x01\x01\x12\x03E\x07\x14\n\x0c\n\x05\x04\x04\x02\x01\
    \x03\x12\x03E\x17\x18\n\x0b\n\x04\x04\x04\x02\x02\x12\x03F\x02\x1a\n\x0c\
    \n\x05\x04\x04\x02\x02\x05\x12\x03F\x02\x06\n\x0c\n\x05\x04\x04\x02\x02\
    \x01\x12\x03F\x07\x15\n\x0c\n\x05\x04\x04\x02\x02\x03\x12\x03F\x18\x19\n\
    \x0b\n\x04\x04\x04\x02\x03\x12\x03G\x02\x17\n\x0c\n\x05\x04\x04\x02\x03\
    \x05\x12\x03G\x02\x06\n\x0c\n\x05\x04\x04\x02\x03\x01\x12\x03G\x07\x12\n\
    \x0c\n\x05\x04\x04\x02\x03\x03\x12\x03G\x15\x16b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(MediaPacket::generated_message_descriptor_data());
            messages.push(RoutingHeader::generated_message_descriptor_data());
            messages.push(AudioMetadata::generated_message_descriptor_data());
            messages.push(VideoMetadata::generated_message_descriptor_data());
            messages.push(HeartbeatMetadata::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(VideoCodec::generated_enum_descriptor_data());
            enums.push(media_packet::MediaType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
