// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/subscription_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:videocall.SubscriptionUpdate)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SubscriptionUpdate {
    // message fields
    // @@protoc_insertion_point(field:videocall.SubscriptionUpdate.pinned_sessions)
    pub pinned_sessions: ::std::vec::Vec<u64>,
    // @@protoc_insertion_point(field:videocall.SubscriptionUpdate.slots)
    pub slots: ::std::vec::Vec<VisibilitySlot>,
    // @@protoc_insertion_point(field:videocall.SubscriptionUpdate.max_video_kbps)
    pub max_video_kbps: u32,
    // @@protoc_insertion_point(field:videocall.SubscriptionUpdate.receive_all_audio)
    pub receive_all_audio: bool,
    ///  vc-3s8: when true, the receiver wants video from every current and
    ///  future member of the room (minus self), capped at MAX_VISIBLE_VIDEO.
    ///  Mirrors `receive_all_audio` for video so a webinar listener that ships
    ///  an opening empty SubscriptionUpdate (visible={}, pinned={},
    ///  receive_all_audio=true) still receives video from senders that join
    ///  AFTER the subscription was applied. Default false preserves the
    ///  existing declarative-replace contract for clients that don't opt in.
    // @@protoc_insertion_point(field:videocall.SubscriptionUpdate.receive_all_video)
    pub receive_all_video: bool,
    // special fields
    // @@protoc_insertion_point(special_field:videocall.SubscriptionUpdate.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SubscriptionUpdate {
    fn default() -> &'a SubscriptionUpdate {
        <SubscriptionUpdate as ::protobuf::Message>::default_instance()
    }
}

impl SubscriptionUpdate {
    pub fn new() -> SubscriptionUpdate {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "pinned_sessions",
            |m: &SubscriptionUpdate| { &m.pinned_sessions },
            |m: &mut SubscriptionUpdate| { &mut m.pinned_sessions },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "slots",
            |m: &SubscriptionUpdate| { &m.slots },
            |m: &mut SubscriptionUpdate| { &mut m.slots },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "max_video_kbps",
            |m: &SubscriptionUpdate| { &m.max_video_kbps },
            |m: &mut SubscriptionUpdate| { &mut m.max_video_kbps },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "receive_all_audio",
            |m: &SubscriptionUpdate| { &m.receive_all_audio },
            |m: &mut SubscriptionUpdate| { &mut m.receive_all_audio },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "receive_all_video",
            |m: &SubscriptionUpdate| { &m.receive_all_video },
            |m: &mut SubscriptionUpdate| { &mut m.receive_all_video },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SubscriptionUpdate>(
            "SubscriptionUpdate",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SubscriptionUpdate {
    const NAME: &'static str = "SubscriptionUpdate";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    is.read_repeated_packed_uint64_into(&mut self.pinned_sessions)?;
                },
                8 => {
                    self.pinned_sessions.push(is.read_uint64()?);
                },
                18 => {
                    self.slots.push(is.read_message()?);
                },
                24 => {
                    self.max_video_kbps = is.read_uint32()?;
                },
                32 => {
                    self.receive_all_audio = is.read_bool()?;
                },
                40 => {
                    self.receive_all_video = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_uint64_size(1, &self.pinned_sessions);
        for value in &self.slots {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.max_video_kbps != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.max_video_kbps);
        }
        if self.receive_all_audio != false {
            my_size += 1 + 1;
        }
        if self.receive_all_video != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_uint64(1, &self.pinned_sessions)?;
        for v in &self.slots {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if self.max_video_kbps != 0 {
            os.write_uint32(3, self.max_video_kbps)?;
        }
        if self.receive_all_audio != false {
            os.write_bool(4, self.receive_all_audio)?;
        }
        if self.receive_all_video != false {
            os.write_bool(5, self.receive_all_video)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SubscriptionUpdate {
        SubscriptionUpdate::new()
    }

    fn clear(&mut self) {
        self.pinned_sessions.clear();
        self.slots.clear();
        self.max_video_kbps = 0;
        self.receive_all_audio = false;
        self.receive_all_video = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SubscriptionUpdate {
        static instance: SubscriptionUpdate = SubscriptionUpdate {
            pinned_sessions: ::std::vec::Vec::new(),
            slots: ::std::vec::Vec::new(),
            max_video_kbps: 0,
            receive_all_audio: false,
            receive_all_video: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SubscriptionUpdate {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SubscriptionUpdate").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SubscriptionUpdate {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SubscriptionUpdate {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:videocall.VisibilitySlot)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct VisibilitySlot {
    // message fields
    // @@protoc_insertion_point(field:videocall.VisibilitySlot.session_id)
    pub session_id: u64,
    // @@protoc_insertion_point(field:videocall.VisibilitySlot.preferred_spatial)
    pub preferred_spatial: u32,
    // @@protoc_insertion_point(field:videocall.VisibilitySlot.preferred_temporal)
    pub preferred_temporal: u32,
    // special fields
    // @@protoc_insertion_point(special_field:videocall.VisibilitySlot.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VisibilitySlot {
    fn default() -> &'a VisibilitySlot {
        <VisibilitySlot as ::protobuf::Message>::default_instance()
    }
}

impl VisibilitySlot {
    pub fn new() -> VisibilitySlot {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "session_id",
            |m: &VisibilitySlot| { &m.session_id },
            |m: &mut VisibilitySlot| { &mut m.session_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "preferred_spatial",
            |m: &VisibilitySlot| { &m.preferred_spatial },
            |m: &mut VisibilitySlot| { &mut m.preferred_spatial },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "preferred_temporal",
            |m: &VisibilitySlot| { &m.preferred_temporal },
            |m: &mut VisibilitySlot| { &mut m.preferred_temporal },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<VisibilitySlot>(
            "VisibilitySlot",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for VisibilitySlot {
    const NAME: &'static str = "VisibilitySlot";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.session_id = is.read_uint64()?;
                },
                16 => {
                    self.preferred_spatial = is.read_uint32()?;
                },
                24 => {
                    self.preferred_temporal = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.session_id != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.session_id);
        }
        if self.preferred_spatial != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.preferred_spatial);
        }
        if self.preferred_temporal != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.preferred_temporal);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.session_id != 0 {
            os.write_uint64(1, self.session_id)?;
        }
        if self.preferred_spatial != 0 {
            os.write_uint32(2, self.preferred_spatial)?;
        }
        if self.preferred_temporal != 0 {
            os.write_uint32(3, self.preferred_temporal)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VisibilitySlot {
        VisibilitySlot::new()
    }

    fn clear(&mut self) {
        self.session_id = 0;
        self.preferred_spatial = 0;
        self.preferred_temporal = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VisibilitySlot {
        static instance: VisibilitySlot = VisibilitySlot {
            session_id: 0,
            preferred_spatial: 0,
            preferred_temporal: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for VisibilitySlot {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("VisibilitySlot").unwrap()).clone()
    }
}

impl ::std::fmt::Display for VisibilitySlot {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VisibilitySlot {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1ftypes/subscription_packet.proto\x12\tvideocall\"\xec\x01\n\x12Subs\
    criptionUpdate\x12'\n\x0fpinned_sessions\x18\x01\x20\x03(\x04R\x0epinned\
    Sessions\x12/\n\x05slots\x18\x02\x20\x03(\x0b2\x19.videocall.VisibilityS\
    lotR\x05slots\x12$\n\x0emax_video_kbps\x18\x03\x20\x01(\rR\x0cmaxVideoKb\
    ps\x12*\n\x11receive_all_audio\x18\x04\x20\x01(\x08R\x0freceiveAllAudio\
    \x12*\n\x11receive_all_video\x18\x05\x20\x01(\x08R\x0freceiveAllVideo\"\
    \x8b\x01\n\x0eVisibilitySlot\x12\x1d\n\nsession_id\x18\x01\x20\x01(\x04R\
    \tsessionId\x12+\n\x11preferred_spatial\x18\x02\x20\x01(\rR\x10preferred\
    Spatial\x12-\n\x12preferred_temporal\x18\x03\x20\x01(\rR\x11preferredTem\
    poralJ\x93\x08\n\x06\x12\x04\0\0\x16\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\
    \n\x08\n\x01\x02\x12\x03\x01\0\x12\n\n\n\x02\x04\0\x12\x04\x03\0\x10\x01\
    \n\n\n\x03\x04\0\x01\x12\x03\x03\x08\x1a\n\x0b\n\x04\x04\0\x02\0\x12\x03\
    \x04\x02&\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03\x04\x02\n\n\x0c\n\x05\x04\
    \0\x02\0\x05\x12\x03\x04\x0b\x11\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x04\
    \x12!\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x04$%\n\x0b\n\x04\x04\0\x02\
    \x01\x12\x03\x05\x02$\n\x0c\n\x05\x04\0\x02\x01\x04\x12\x03\x05\x02\n\n\
    \x0c\n\x05\x04\0\x02\x01\x06\x12\x03\x05\x0b\x19\n\x0c\n\x05\x04\0\x02\
    \x01\x01\x12\x03\x05\x1a\x1f\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x05\"\
    #\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x06\x02\x1c\n\x0c\n\x05\x04\0\x02\
    \x02\x05\x12\x03\x06\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x06\t\
    \x17\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x06\x1a\x1b\n\x1f\n\x04\x04\0\
    \x02\x03\x12\x03\x07\x02\x1d\"\x12\x20v1\x20default:\x20true\n\n\x0c\n\
    \x05\x04\0\x02\x03\x05\x12\x03\x07\x02\x06\n\x0c\n\x05\x04\0\x02\x03\x01\
    \x12\x03\x07\x07\x18\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x07\x1b\x1c\n\
    \xe9\x03\n\x04\x04\0\x02\x04\x12\x03\x0f\x02\x1d\x1a\xdb\x03\x20vc-3s8:\
    \x20when\x20true,\x20the\x20receiver\x20wants\x20video\x20from\x20every\
    \x20current\x20and\n\x20future\x20member\x20of\x20the\x20room\x20(minus\
    \x20self),\x20capped\x20at\x20MAX_VISIBLE_VIDEO.\n\x20Mirrors\x20`receiv\
    e_all_audio`\x20for\x20video\x20so\x20a\x20webinar\x20listener\x20that\
    \x20ships\n\x20an\x20opening\x20empty\x20SubscriptionUpdate\x20(visible=\
    {},\x20pinned={},\n\x20receive_all_audio=true)\x20still\x20receives\x20v\
    ideo\x20from\x20senders\x20that\x20join\n\x20AFTER\x20the\x20subscriptio\
    n\x20was\x20applied.\x20Default\x20false\x20preserves\x20the\n\x20existi\
    ng\x20declarative-replace\x20contract\x20for\x20clients\x20that\x20don't\
    \x20opt\x20in.\n\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\x0f\x02\x06\n\x0c\
    \n\x05\x04\0\x02\x04\x01\x12\x03\x0f\x07\x18\n\x0c\n\x05\x04\0\x02\x04\
    \x03\x12\x03\x0f\x1b\x1c\n\n\n\x02\x04\x01\x12\x04\x12\0\x16\x01\n\n\n\
    \x03\x04\x01\x01\x12\x03\x12\x08\x16\n\x0b\n\x04\x04\x01\x02\0\x12\x03\
    \x13\x02\x18\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\x13\x02\x08\n\x0c\n\
    \x05\x04\x01\x02\0\x01\x12\x03\x13\t\x13\n\x0c\n\x05\x04\x01\x02\0\x03\
    \x12\x03\x13\x16\x17\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\x14\x02\x1f\n\
    \x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x14\x02\x08\n\x0c\n\x05\x04\x01\
    \x02\x01\x01\x12\x03\x14\t\x1a\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\
    \x14\x1d\x1e\n\x0b\n\x04\x04\x01\x02\x02\x12\x03\x15\x02\x20\n\x0c\n\x05\
    \x04\x01\x02\x02\x05\x12\x03\x15\x02\x08\n\x0c\n\x05\x04\x01\x02\x02\x01\
    \x12\x03\x15\t\x1b\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x15\x1e\x1fb\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(SubscriptionUpdate::generated_message_descriptor_data());
            messages.push(VisibilitySlot::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
